### ISSUE TITLE
Patch files

### ISSUE THREAD

**Issue by Herst** [bm16ton/linux-4.14_16ton#1]
Hi, sounds great what you did here but would it also be possible to add your changes additionally as `patch` files? This way it would be easier to track what changed and rebase the patches onto other kernel versions/forks.

**Comment by bm16ton** [comment]
sure, give me 24 hours. I didnt add it to README or any posts anywhere but the atheros ath9k with this kernel supports channels 0 thru -19 plus a couple more above channel 14 up to 65, needs my iw and hostap patches which are in tools/16ton. tho i hope only people with ham license use them. im gonna try and see if i can do the same with brcmfmac card in  GPD-WIN

**Comment by bm16ton** [comment]
Ok I think i got all or at least the important patches, placed in CURRENTLY_APPLIED_PATCHES. Tho i expect plenty more to come

**Comment by Herst** [comment]
Very nice, thank you!
